// list of domains from https://developers.google.com/tag-manager/web/csp
const google = {
  connectSrc: [
    'https://www.google.com',
    'https://www.google.ca',
    'https://www.google.co.uk',
    'https://www.google.de',
    'https://www.google.co.jp',
    'https://www.google.fr',
    'https://www.google.com.au',
    'https://www.google.co.in',
    'https://www.google.co.kr',
    'https://www.google.ru',
    'https://www.google.com.br',
    'https://www.google.com.mx',
    'https://www.google.com.id',
    'https://www.google.com.tr',
    'https://www.google.ch',
    'https://www.google.it',
    'https://www.google.nl',
    'https://www.google.se',
    'https://www.google.no',
    'https://www.google.es',
    'https://www.google.com.ua',
    'https://stats.g.doubleclick.net',
    'https://*.googleapis.com',
    'https://*.google-analytics.com',
  ],
  fontSrc: ['https://fonts.gstatic.com'],
  frameSrc: [
    'https://bid.g.doubleclick.net',
    'https://www.google.com',
    'https://tpc.googlesyndication.com',
  ],
  imgSrc: [
    'https://cm.g.doubleclick.net',
    'https://storage.googleapis.com/unstoppable-client-assets/',
    'https://storage.googleapis.com/unstoppable-client-assets-staging/',
    'https://www.gstatic.com',
    'https://www.google-analytics.com',
    'https://www.googletagmanager.com',
    'https://ssl.gstatic.com',
    'https://googleads.g.doubleclick.net',
    'https://*.googleadservices.com',
    'https://www.google.com',
    'https://www.google.ca',
    'https://www.google.co.uk',
    'https://www.google.de',
    'https://www.google.co.jp',
    'https://www.google.fr',
    'https://www.google.com.au',
    'https://www.google.co.in',
    'https://www.google.co.kr',
    'https://www.google.ru',
    'https://www.google.com.br',
    'https://www.google.com.mx',
    'https://www.google.com.id',
    'https://www.google.com.tr',
    'https://www.google.ch',
    'https://www.google.it',
    'https://www.google.nl',
    'https://www.google.se',
    'https://www.google.no',
    'https://www.google.es',
    'https://www.google.com.ua',
  ],
  mediaSrc: ['https://storage.googleapis.com/unstoppable-client-assets/'],
  scriptSrc: [
    'https://apis.google.com',
    'http://www.google-analytics.com',
    'https://www.google-analytics.com',
    'https://ssl.google-analytics.com',
    'https://www.googletagmanager.com',
    'https://tagmanager.google.com',
    'https://www.googleadservices.com',
    'https://www.google.com',
    'https://googleads.g.doubleclick.net',
    'https://www.googletagmanager.com',
    'http://www.googletagmanager.com',
    'https://www.gstatic.com',
    'https://tpc.googlesyndication.com',
  ],
  styleSrc: ['https://fonts.googleapis.com/', 'https://tagmanager.google.com'],
};

module.exports = google;
