export enum AdditionalCurrenciesEnum {
  ZIL = 'ZIL',
  LTC = 'LTC',
  XRP = 'XRP',
  ETC = 'ETC',
  EQL = 'EQL',
  LINK = 'LINK',
  USDC = 'USDC',
  BAT = 'BAT',
  REP = 'REP',
  ZRX = 'ZRX',
  DAI = 'DAI',
  BCH = 'BCH',
  XMR = 'XMR',
  DASH = 'DASH',
  NEO = 'NEO',
  DOGE = 'DOGE',
  ZEC = 'ZEC',
  EOS = 'EOS',
  XLM = 'XLM',
  BNB = 'BNB',
  BTG = 'BTG',
  NANO = 'NANO',
  WAVES = 'WAVES',
  KMD = 'KMD',
  AE = 'AE',
  RSK = 'RSK',
  WAN = 'WAN',
  STRAT = 'STRAT',
  UBQ = 'UBQ',
  XTZ = 'XTZ',
  MIOTA = 'MIOTA',
  VET = 'VET',
  QTUM = 'QTUM',
  ICX = 'ICX',
  DGB = 'DGB',
  XZC = 'XZC',
  BURST = 'BURST',
  DCR = 'DCR',
  XEM = 'XEM',
  LSK = 'LSK',
  ATOM = 'ATOM',
  ONG = 'ONG',
  ONT = 'ONT',
  SMART = 'SMART',
  TPAY = 'TPAY',
  GRS = 'GRS',
  BSV = 'BSV',
  GAS = 'GAS',
  TRX = 'TRX',
  VTHO = 'VTHO',
  BCD = 'BCD',
  BTT = 'BTT',
  KIN = 'KIN',
  RVN = 'RVN',
  ARK = 'ARK',
  XVG = 'XVG',
  ALGO = 'ALGO',
  NEBL = 'NEBL',
  BNTY = 'BNTY',
  ONE = 'ONE',
  SWTH = 'SWTH',
  CRO = 'CRO',
  TWT = 'TWT',
  SIERRA = 'SIERRA',
  VSYS = 'VSYS',
  HIVE = 'HIVE',
  HT = 'HT',
  ENJ = 'ENJ',
  YFI = 'YFI',
  MTA = 'MTA',
  COMP = 'COMP',
  BAL = 'BAL',
  AMPL = 'AMPL',
  LEND = 'AAVE',
  USDT = 'USDT',
  FTM = 'FTM',
  FUSE = 'FUSE',
  TLOS = 'TLOS',
  XDC = 'XDC',
  AR = 'AR',
  NIM = 'NIM',
  MATIC = 'MATIC',
  CUSDT = 'CUSDT',
  AVAX = 'AVAX',
  DOT = 'DOT',
  BUSD = 'BUSD',
  SHIB = 'SHIB',
  LUNA = 'LUNA',
  CAKE = 'CAKE',
  MANA = 'MANA',
  EGLD = 'EGLD',
  SAND = 'SAND',
  WAXP = 'WAXP',
  '1INCH' = '1INCH',
  THETA = 'THETA',
  HNT = 'HNT',
  SAFEMOON = 'SAFEMOON',
  NEAR = 'NEAR',
  FIL = 'FIL',
  AXS = 'AXS',
  AMP = 'AMP',
  CELO = 'CELO',
  KSM = 'KSM',
  CSPR = 'CSPR',
  UNI = 'UNI',
  CEL = 'CEL',
  ERG = 'ERG',
  KAVA = 'KAVA',
  LRC = 'LRC',
  POLY = 'POLY',
  TFUEL = 'TFUEL',
  NEXO = 'NEXO',
  FLOW = 'FLOW',
  ICP = 'ICP',
  TUSD = 'TUSD',
  KLV = 'KLV',
  BLOCKS = 'BLOCKS',
  YLD = 'YLD',
  OKT = 'OKT',
  B2M = 'B2M',
  DOG = 'DOG',
  GALA = 'GALA',
  MOBX = 'MOBX',
  FAB = 'FAB',
  FIRO = 'FIRO',
  FET = 'FET',
  BEAM = 'BEAM',
  '0ZK' = '0ZK',
  SUI = 'SUI',
  MOON = 'MOON',
  SWEAT = 'SWEAT',
  DESO = 'DESO',
  FLR = 'FLR',
  SGB = 'SGB',
  POKT = 'POKT',
  XLA = 'XLA',
  KAI = 'KAI',
  APT = 'APT',
  GTH = 'GTH',
  HI = 'HI',
  MCONTENT = 'MCONTENT',
  VERSE = 'VERSE',
}

enum InitialCurrenciesEnum {
  BTC = 'BTC',
  ETH = 'ETH',
  ADA = 'ADA',
  SOL = 'SOL',
  HBAR = 'HBAR',
}

export const AllCurrencies = {
  ...InitialCurrenciesEnum,
  ...AdditionalCurrenciesEnum,
};

export type AllCurrenciesType =
  | InitialCurrenciesEnum
  | AdditionalCurrenciesEnum;

export enum Blockchain {
  ETH = 'ETH',
  ZIL = 'ZIL',
  MATIC = 'MATIC',
}

export type EvmBlockchain = Blockchain.ETH | Blockchain.MATIC;

export type Meta = {
  logicalOwnerAddress: string | null;
  blockchain: Blockchain | null;
  type: Registry;
  ttl: number;
  tokenId?: string;
  domain: string;
  namehash: string;
  registryAddress: string | null;
  resolver: string | null;
  reverse: boolean;
};

export enum Mirror {
  UNS = 'UNS',
  ENS = 'ENS',
  ZNS = 'ZNS',
}

export enum Registry {
  CNS = 'CNS',
  UNS = 'UNS',
  ENS = 'ENS',
}
